# Verified July 2026. Sources: Wikipedia league lists; EPL 2026-27 via 2025-26 final table
# and 2026 EFL Championship play-off final; FBS list incl. 2026 joiners NDSU & Sacramento State.

MLB = ["Arizona Diamondbacks","Athletics","Atlanta Braves","Baltimore Orioles","Boston Red Sox",
"Chicago Cubs","Chicago White Sox","Cincinnati Reds","Cleveland Guardians","Colorado Rockies",
"Detroit Tigers","Houston Astros","Kansas City Royals","Los Angeles Angels","Los Angeles Dodgers",
"Miami Marlins","Milwaukee Brewers","Minnesota Twins","New York Mets","New York Yankees",
"Philadelphia Phillies","Pittsburgh Pirates","San Diego Padres","San Francisco Giants",
"Seattle Mariners","St. Louis Cardinals","Tampa Bay Rays","Texas Rangers","Toronto Blue Jays",
"Washington Nationals"]

NBA = ["Atlanta Hawks","Boston Celtics","Brooklyn Nets","Charlotte Hornets","Chicago Bulls",
"Cleveland Cavaliers","Dallas Mavericks","Denver Nuggets","Detroit Pistons","Golden State Warriors",
"Houston Rockets","Indiana Pacers","Los Angeles Clippers","Los Angeles Lakers","Memphis Grizzlies",
"Miami Heat","Milwaukee Bucks","Minnesota Timberwolves","New Orleans Pelicans","New York Knicks",
"Oklahoma City Thunder","Orlando Magic","Philadelphia 76ers","Phoenix Suns","Portland Trail Blazers",
"Sacramento Kings","San Antonio Spurs","Toronto Raptors","Utah Jazz","Washington Wizards"]

NHL = ["Anaheim Ducks","Boston Bruins","Buffalo Sabres","Calgary Flames","Carolina Hurricanes",
"Chicago Blackhawks","Colorado Avalanche","Columbus Blue Jackets","Dallas Stars","Detroit Red Wings",
"Edmonton Oilers","Florida Panthers","Los Angeles Kings","Minnesota Wild","Montreal Canadiens",
"Nashville Predators","New Jersey Devils","New York Islanders","New York Rangers","Ottawa Senators",
"Philadelphia Flyers","Pittsburgh Penguins","San Jose Sharks","Seattle Kraken","St. Louis Blues",
"Tampa Bay Lightning","Toronto Maple Leafs","Utah Mammoth","Vancouver Canucks","Vegas Golden Knights",
"Washington Capitals","Winnipeg Jets"]

NFL = ["Arizona Cardinals","Atlanta Falcons","Baltimore Ravens","Buffalo Bills","Carolina Panthers",
"Chicago Bears","Cincinnati Bengals","Cleveland Browns","Dallas Cowboys","Denver Broncos",
"Detroit Lions","Green Bay Packers","Houston Texans","Indianapolis Colts","Jacksonville Jaguars",
"Kansas City Chiefs","Las Vegas Raiders","Los Angeles Chargers","Los Angeles Rams","Miami Dolphins",
"Minnesota Vikings","New England Patriots","New Orleans Saints","New York Giants","New York Jets",
"Philadelphia Eagles","Pittsburgh Steelers","San Francisco 49ers","Seattle Seahawks",
"Tampa Bay Buccaneers","Tennessee Titans","Washington Commanders"]

EPL = ["Arsenal","Aston Villa","Bournemouth","Brentford","Brighton & Hove Albion","Chelsea",
"Coventry City","Crystal Palace","Everton","Fulham","Hull City","Ipswich Town","Leeds United",
"Liverpool","Manchester City","Manchester United","Newcastle United","Nottingham Forest",
"Sunderland","Tottenham Hotspur"]

NCAAF = ["Air Force","Akron","Alabama","Appalachian State","Arizona","Arizona State","Arkansas",
"Arkansas State","Army","Auburn","Ball State","Baylor","Boise State","Boston College","Bowling Green",
"Buffalo","BYU","California","Central Michigan","Charlotte","Cincinnati","Clemson","Coastal Carolina",
"Colorado","Colorado State","Delaware","Duke","East Carolina","Eastern Michigan","FIU","Florida",
"Florida Atlantic","Florida State","Fresno State","Georgia","Georgia Southern","Georgia State",
"Georgia Tech","Hawaii","Houston","Illinois","Indiana","Iowa","Iowa State","Jacksonville State",
"James Madison","Kansas","Kansas State","Kennesaw State","Kent State","Kentucky","Liberty",
"Louisiana","Louisiana Tech","Louisville","LSU","Marshall","Maryland","Memphis","Miami (FL)",
"Miami (OH)","Michigan","Michigan State","Middle Tennessee","Minnesota","Mississippi State",
"Missouri","Missouri State","Navy","NC State","Nebraska","Nevada","New Mexico","New Mexico State",
"North Carolina","North Dakota State","North Texas","Northern Illinois","Northwestern","Notre Dame",
"Ohio","Ohio State","Oklahoma","Oklahoma State","Old Dominion","Ole Miss","Oregon","Oregon State",
"Penn State","Pittsburgh","Purdue","Rice","Rutgers","Sacramento State","Sam Houston","San Diego State",
"San Jose State","SMU","South Alabama","South Carolina","South Florida","Southern Miss","Stanford",
"Syracuse","TCU","Temple","Tennessee","Texas","Texas A&M","Texas State","Texas Tech","Toledo","Troy",
"Tulane","Tulsa","UAB","UCF","UCLA","UConn","ULM","UMass","UNLV","USC","Utah","Utah State","UTEP",
"UTSA","Vanderbilt","Virginia","Virginia Tech","Wake Forest","Washington","Washington State",
"West Virginia","Western Kentucky","Western Michigan","Wisconsin","Wyoming"]

NCAAM = ["Abilene Christian","Air Force","Akron","Alabama","Alabama A&M","Alabama State","Albany",
"Alcorn State","American","Appalachian State","Arizona","Arizona State","Arkansas","Arkansas State",
"Arkansas-Pine Bluff","Army","Auburn","Austin Peay","Ball State","Baylor","Bellarmine","Belmont",
"Bethune-Cookman","Binghamton","Boise State","Boston College","Boston University","Bowling Green",
"Bradley","Brown","Bryant","Bucknell","Buffalo","Butler","BYU","Cal Poly","Cal State Bakersfield",
"Cal State Fullerton","Cal State Northridge","California","California Baptist","Campbell","Canisius",
"Central Arkansas","Central Connecticut","Central Michigan","Charleston","Charleston Southern",
"Charlotte","Chattanooga","Chicago State","Cincinnati","The Citadel","Clemson","Cleveland State",
"Coastal Carolina","Colgate","Colorado","Colorado State","Columbia","Coppin State","Cornell",
"Creighton","Dartmouth","Davidson","Dayton","Delaware","Delaware State","Denver","DePaul",
"Detroit Mercy","Drake","Drexel","Duke","Duquesne","East Carolina","East Tennessee State",
"East Texas A&M","Eastern Illinois","Eastern Kentucky","Eastern Michigan","Eastern Washington",
"Elon","Evansville","Fairfield","Fairleigh Dickinson","FIU","Florida","Florida A&M",
"Florida Atlantic","Florida Gulf Coast","Florida State","Fordham","Fresno State","Furman",
"Gardner-Webb","George Mason","George Washington","Georgetown","Georgia","Georgia Southern",
"Georgia State","Georgia Tech","Gonzaga","Grambling State","Grand Canyon","Green Bay","Hampton",
"Harvard","Hawaii","High Point","Hofstra","Holy Cross","Houston","Houston Christian","Howard",
"Idaho","Idaho State","Illinois","Illinois State","Incarnate Word","Indiana","Indiana State","Iona",
"Iowa","Iowa State","IU Indianapolis","Jackson State","Jacksonville","Jacksonville State",
"James Madison","Kansas","Kansas City","Kansas State","Kennesaw State","Kent State","Kentucky",
"La Salle","Lafayette","Lamar","Le Moyne","Lehigh","Liberty","Lindenwood","Lipscomb","Little Rock",
"LIU","Long Beach State","Longwood","Louisiana","Louisiana Tech","Louisville","Loyola Chicago",
"Loyola Maryland","Loyola Marymount","LSU","Maine","Manhattan","Marist","Marquette","Marshall",
"Maryland","Maryland Eastern Shore","McNeese","Memphis","Mercer","Mercyhurst","Merrimack",
"Miami (FL)","Miami (OH)","Michigan","Michigan State","Middle Tennessee","Milwaukee","Minnesota",
"Mississippi State","Mississippi Valley State","Missouri","Missouri State","Monmouth","Montana",
"Montana State","Morehead State","Morgan State","Mount St. Mary's","Murray State","Navy","NC State",
"Nebraska","Nevada","New Hampshire","New Haven","New Mexico","New Mexico State","New Orleans",
"Niagara","Nicholls","NJIT","Norfolk State","North Alabama","North Carolina","North Carolina A&T",
"North Carolina Central","North Dakota","North Dakota State","North Florida","North Texas",
"Northeastern","Northern Arizona","Northern Colorado","Northern Illinois","Northern Iowa",
"Northern Kentucky","Northwestern","Northwestern State","Notre Dame","Oakland","Ohio","Ohio State",
"Oklahoma","Oklahoma State","Old Dominion","Ole Miss","Omaha","Oral Roberts","Oregon","Oregon State",
"Pacific","Penn","Penn State","Pepperdine","Pittsburgh","Portland","Portland State",
"Prairie View A&M","Presbyterian","Princeton","Providence","Purdue","Purdue Fort Wayne",
"Queens (NC)","Quinnipiac","Radford","Rhode Island","Rice","Richmond","Rider","Robert Morris",
"Rutgers","Sacramento State","Sacred Heart","Saint Joseph's","Saint Louis","Saint Mary's (CA)",
"Saint Peter's","Sam Houston","Samford","San Diego","San Diego State","San Francisco",
"San Jose State","Santa Clara","Seattle","Seton Hall","Siena","SIU Edwardsville","SMU",
"South Alabama","South Carolina","South Carolina State","South Dakota","South Dakota State",
"South Florida","Southeast Missouri State","Southeastern Louisiana","Southern","Southern Illinois",
"Southern Indiana","Southern Miss","Southern Utah","St. Bonaventure","St. John's","St. Thomas (MN)",
"Stanford","Stephen F. Austin","Stetson","Stonehill","Stony Brook","Syracuse","Tarleton State","TCU",
"Temple","Tennessee","Tennessee State","Tennessee Tech","Texas","Texas A&M",
"Texas A&M-Corpus Christi","Texas Southern","Texas State","Texas Tech","Toledo","Towson","Troy",
"Tulane","Tulsa","UAB","UC Davis","UC Irvine","UC Riverside","UC San Diego","UC Santa Barbara",
"UCF","UCLA","UConn","UIC","UL Monroe","UMass","UMass Lowell","UMBC","UNC Asheville",
"UNC Greensboro","UNC Wilmington","UNLV","USC","USC Upstate","UT Arlington","UT Martin","Utah",
"Utah State","Utah Tech","Utah Valley","UTEP","UTRGV","UTSA","Valparaiso","Vanderbilt","VCU",
"Vermont","Villanova","Virginia","Virginia Tech","VMI","Wagner","Wake Forest","Washington",
"Washington State","Weber State","West Florida","West Georgia","West Virginia","Western Carolina",
"Western Illinois","Western Kentucky","Western Michigan","Wichita State","William & Mary",
"Winthrop","Wisconsin","Wofford","Wright State","Wyoming","Xavier","Yale","Youngstown State"]

LEAGUES = [
    ("MLB", MLB, "World Series"),
    ("NBA", NBA, "NBA Finals"),
    ("NHL", NHL, "Stanley Cup"),
    ("NFL", NFL, "Super Bowl"),
    ("NCAAF", NCAAF, "CFP National Championship"),
    ("NCAAM", NCAAM, "NCAA Tournament"),
    ("EPL", EPL, "Premier League Title"),
]

# Championship futures odds as of July 2026 (All-Star break). REFRESH BEFORE DRAFT DAY 2027.
ODDS = {
    "MLB": ("2026 World Series", "BetMGM via VegasInsider", [
        ("Los Angeles Dodgers",180),("New York Yankees",550),("Milwaukee Brewers",1000),
        ("Atlanta Braves",1200),("Seattle Mariners",1200),("Philadelphia Phillies",1200),
        ("Tampa Bay Rays",1700),("Chicago Cubs",2000),("Texas Rangers",2500),
        ("Cleveland Guardians",3000),("Toronto Blue Jays",3500),("Chicago White Sox",4000),
        ("Boston Red Sox",4000),("Detroit Tigers",5000),("Houston Astros",6000),
        ("Pittsburgh Pirates",8000),("Baltimore Orioles",10000),("Miami Marlins",10000),
        ("San Diego Padres",10000),("Minnesota Twins",12500)]),
    "NBA": ("2027 NBA Championship", "BetMGM via VegasInsider", [
        ("Oklahoma City Thunder",260),("San Antonio Spurs",260),("New York Knicks",900),
        ("Boston Celtics",1400),("Philadelphia 76ers",1800),("Cleveland Cavaliers",2000),
        ("Toronto Raptors",2200),("Miami Heat",2500),("Denver Nuggets",2500),
        ("Minnesota Timberwolves",2500),("Detroit Pistons",2500),("Golden State Warriors",3000),
        ("Los Angeles Lakers",3500),("Indiana Pacers",4000),("Houston Rockets",6000),
        ("Atlanta Hawks",8000),("Portland Trail Blazers",8000),("Orlando Magic",8000),
        ("Charlotte Hornets",12500),("Phoenix Suns",12500)]),
    "NHL": ("2027 Stanley Cup", "DraftKings via CBS Sports", [
        ("Carolina Hurricanes",700),("Colorado Avalanche",800),("Vegas Golden Knights",850),
        ("Edmonton Oilers",1100),("Florida Panthers",1100),("Tampa Bay Lightning",1200),
        ("Minnesota Wild",1400),("Dallas Stars",1500),("Ottawa Senators",1600),
        ("Montreal Canadiens",2200),("Anaheim Ducks",2500),("Buffalo Sabres",2500),
        ("Los Angeles Kings",3000),("New Jersey Devils",3000),("Utah Mammoth",3000),
        ("Columbus Blue Jackets",3500),("Toronto Maple Leafs",4000),("Philadelphia Flyers",5000),
        ("Washington Capitals",5000),("Pittsburgh Penguins",5500)]),
    "NFL": ("Super Bowl LXI (2026 season)", "DraftKings via VegasInsider", [
        ("Los Angeles Rams",550),("Baltimore Ravens",1000),("Buffalo Bills",1000),
        ("Seattle Seahawks",1100),("New England Patriots",1600),("Kansas City Chiefs",1600),
        ("Philadelphia Eagles",1600),("Los Angeles Chargers",1700),("Houston Texans",1800),
        ("Green Bay Packers",1800),("San Francisco 49ers",1900),("Detroit Lions",1900),
        ("Cincinnati Bengals",2000),("Denver Broncos",2000),("Chicago Bears",2500),
        ("Dallas Cowboys",2500),("Jacksonville Jaguars",3000),("Minnesota Vikings",5000),
        ("Tampa Bay Buccaneers",5000),("Pittsburgh Steelers",5000)]),
    "NCAAF": ("2026-27 CFP National Championship", "VegasInsider consensus", [
        ("Ohio State",600),("Notre Dame",700),("Texas",750),("Indiana",750),("Oregon",800),
        ("Georgia",900),("Miami (FL)",1200),("LSU",1500),("Texas A&M",1500),("Alabama",1500),
        ("Texas Tech",2200),("Ole Miss",2500),("Michigan",2500),("Oklahoma",3000),("USC",3500),
        ("Penn State",5000),("Tennessee",5000),("Clemson",5000),("Florida",6000),("Auburn",6600)]),
    "NCAAM": ("2027 NCAA Tournament Champion", "Bovada", [
        ("Florida",600),("Duke",700),("Michigan",1200),("UConn",1200),("Illinois",1300),
        ("Arizona",1800),("Arkansas",1900),("Houston",2200),("Louisville",2200),
        ("Michigan State",2200),("Texas",2200),("Kansas",2500),("Gonzaga",2500),
        ("St. John's",3500),("Virginia",3500),("Alabama",4000),("Iowa State",4000),
        ("Kentucky",4000),("North Carolina",4000),("Texas Tech",4000)]),
    "EPL": ("2026-27 Premier League Winner", "Hard Rock Bet", [
        ("Arsenal",150),("Manchester City",250),("Liverpool",500),("Manchester United",700),
        ("Chelsea",1000),("Aston Villa",2500),("Newcastle United",4000),
        ("Brighton & Hove Albion",15000),("Bournemouth",20000),("Brentford",25000),
        ("Everton",25000),("Crystal Palace",50000),("Fulham",50000),("Leeds United",50000),
        ("Nottingham Forest",50000),("Sunderland",100000),("Coventry City",100000),
        ("Ipswich Town",100000)]),
}
